backend:
  name: git-gateway
  #name: github
  #repo: arts-nthu/website
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "index"
    label: "封面輪播"
    folder: "content/zh-tw/_index.md"
    create: false
    fields:
      - { label: "內容", name: "body", widget: "markdown" }
  - name: "post"
    label: "專欄"
    folder: "content/zh-tw/posts"
    create: true
    slug: "{{start_date}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "封面圖片", name: "cover", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - label: "標籤"
        name: "tags"
        widget: "select"
        multiple: true
        options: []
      - { label: "草稿", name: "draft", widget: "boolean", default: false }
      - { label: "內容", name: "body", widget: "markdown" }
  - name: "exhibition" # Used in routes, e.g., /admin/collections/blog
    label: "展覽" # Used in the UI
    folder: "content/zh-tw/exhibitions" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{start_date}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "標題", name: "title", widget: "string" }
      - { label: "封面圖片", name: "cover", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - label: "類型"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["visual_art", "public_art", "performing_art", "film_art", "ai_music"]
      - label: "主辦單位"
        name: "host"
        widget: "string"
        default: "清華大學藝術中心"
        required: false 
      - label: "表演者"
        name: "performer"
        widget: "string"
        required: false
      - label: "地點"
        name: "location"
        widget: "string"
        required: false
      - label: "開始日期"
        name: "start_date"
        widget: "datetime"
        format: "'YYYY-MM-DD'"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "結束日期"
        name: "end_date"
        widget: "datetime"
        format: "'YYYY-MM-DD'"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: "開始時間"
        name: "daily_start_time"
        widget: "datetime"
        format: "'HH:mm'"
        dateFormat: "HH:mm"
        required: false
      - label: "結束時間"
        name: "daily_end_time"
        widget: "datetime"
        format: "'HH:mm'"
        dateFormat: "HH:mm"
        required: false
      - label: "票務資訊"
        name: "ticket_info"
        widget: "string"
        required: false
        default: ''
      - label: "註冊連結"
        name: "registration_link"
        required: false
        default: ''

      - { label: "內容", name: "body", widget: "markdown" }
